# services:
#   - name: wagtail-react
#     type: web
#     env: python
#     repo: https://gitlab.com/stackingtabs/wagtail-react.git
#     buildCommand: ./build.sh
#     startCommand: gunicorn mysite.wsgi:application
#     envVars:
#       - key: SECRET_KEY
#         generateValue: true

databases:
  - name: anime-listings
    databaseName: django
    user: django

services:
  - type: web
    name: anime-listings
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: anime-listings
          property: connectionString
      # - key: DJANGO_SECRET_KEY
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ADMIN_URL
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.production
